{
 "title": "Python AIOHTTP dashboard",
 "description": "Dashboard for AIOHTTP python library https://github.com/RailYakup/aiohttp-prometheus",
 "tags": [
  "aiohttp",
  "python"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(aiohttp_http_request_duration_seconds_bucket,namespace)"
   },
   {
    "name": "job",
    "query": "label_values(aiohttp_http_request_duration_seconds_bucket{namespace=\"$namespace\"},job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Python runtime version",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "python_info{namespace=\"$namespace\",job=\"$job\"}"
    }
   ]
  },
  { "title": "HTTP statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aiohttp_http_requests_total{namespace=\"$namespace\",job=\"$job\",handler!=\"MetricsView\"}[$__rate_interval])) by(job,method,status)",
     "legendFormat": "{{job}}/{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Latency HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(aiohttp_http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"$job\",handler!=\"MetricsView\"}[$__rate_interval])) by(job,le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC collected objects",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_gc_objects_collected_total{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{job}}/generation-{{generation}}"
      }
     ]
    },
    {
     "title": "GC uncollectable objects",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_gc_objects_uncollectable_total{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{job}}/generation-{{generation}}"
      }
     ]
    },
    {
     "title": "GC number of collections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "python_gc_collections_total{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{job}}/generation-{{generation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Virtual Memory size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Resident Memory size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Number of open files",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{namespace=\"$namespace\",job=\"$job\"}",
       "legendFormat": "{{job}}/open-files"
      }
     ]
    }
   ]
  }
 ]
}