---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis.conf: |-
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
    supervised no
    daemonize no
    loglevel notice
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 150mb
    maxmemory-policy volatile-ttl
    requirepass {{ .Values.envVarsSecret.REDIS_PASS }}