apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myteam-alertmanager-bot.fullname" . }}-alert-template
data:
{{- with .Values.alertTemplate }}
  alert_template.j2: |-
    {{- . | nindent 4 }}
{{- end }}
