{{- if .Values.envVarsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myteam-alertmanager-bot.fullname" . }}
data:
  {{- range $key, $val := .Values.envVarsSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end }}
